# Jellyfin Media Server

services:
  jellyfin:
    image: ${JELLYFIN_IMAGE}:${JELLYFIN_TAG}
    env_file:
      - ../.env.defaults
      - ../.env.local
    container_name: jellyfin
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${JELLYFIN_UID}
      - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
      - UMASK=002
    volumes:
      - ${ROOT_DIR}/config/jellyfin-config:/config
      - ${ROOT_DIR}/data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8096/health | grep -q Healthy && test -d /data/realdebrid-zurg && mountpoint -q /data/realdebrid-zurg"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      overseerr:
        condition: service_healthy
        restart: true
      rclone:
        condition: service_healthy
        restart: true
    labels:
    - traefik.enable=true
    - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_TRAEFIK_NAME}.${DOMAIN_NAME}`)
    - traefik.http.routers.jellyfin.entrypoints=websecure
    - traefik.http.routers.jellyfin.tls=true
    - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
    - traefik.http.routers.jellyfin-http.rule=Host(`${JELLYFIN_TRAEFIK_NAME}.${DOMAIN_NAME}`)
    - traefik.http.routers.jellyfin-http.entrypoints=web
    - traefik.http.routers.jellyfin-http.middlewares=jellyfin-https-redirect
    - traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https
    - traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.permanent=true
    - traefik.http.services.jellyfin.loadbalancer.server.url=http://${MEDIACENTER_GATEWAY_IP}:${JELLYFIN_PORT}
